#!/usr/bin/env bash
# Step 1 of first-time air-gap setup — RUN FROM THE USB (or any path; needs USB mounted).
#
#   sudo authorize-offline-usb.sh          # if needed
#   sudo mount-offline-usb.sh              # or mount -L RHEL8OFFLINE /mnt/rhel8offline
#   sudo bash /mnt/rhel8offline/scripts/copy-offline-mirror-from-usb.sh
#
# Does:
#   - install helpers/docs early from USB
#   - rsync full offline mirror USB → LOCAL disk
#   - point dnf at local mirror
#   - reinstall helpers from local copy (so later steps do not need USB)
#   - does NOT unmount USB (you do that) and does NOT install packages
#
# Then:
#   sudo umount /mnt/rhel8offline
#   # remove USB
#   sudo install-from-local-mirror.sh
#
# Env:
#   USB_REPO_LABEL   default RHEL8OFFLINE
#   USB_MNT          default /mnt/rhel8offline
#   LOCAL_REPO_ROOT  default /var/lib/offline-repos
#   SKIP_REPO_COPY=1 skip rsync if local mirror already complete
set -euo pipefail

LABEL="${USB_REPO_LABEL:-RHEL8OFFLINE}"
USB_MNT="${USB_MNT:-${MNT:-/mnt/rhel8offline}}"
LOCAL_REPO_ROOT="${LOCAL_REPO_ROOT:-/var/lib/offline-repos}"
REPO_FILE_LOCAL="/etc/yum.repos.d/offline-local.repo"
REPO_FILE_USB="/etc/yum.repos.d/offline-usb.repo"
SKIP_REPO_COPY="${SKIP_REPO_COPY:-0}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root" >&2
  exit 1
fi

log() { echo "==> $*"; }

authorize_usb_for_offline_media() {
  if [[ -x /usr/local/sbin/authorize-offline-usb.sh ]]; then
    log "Running authorize-offline-usb.sh"
    /usr/local/sbin/authorize-offline-usb.sh || true
    return 0
  fi
  log "USB authorize (inline): stop USBGuard, authorize devices, load hid/storage"
  systemctl stop usbguard.service usbguard-dbus.service 2>/dev/null || true
  systemctl disable usbguard.service usbguard-dbus.service 2>/dev/null || true
  if [[ -f /sys/module/usbcore/parameters/authorized_default ]]; then
    echo 1 > /sys/module/usbcore/parameters/authorized_default 2>/dev/null || true
  fi
  for auth in /sys/bus/usb/devices/*/authorized; do
    [[ -f "$auth" ]] && echo 1 > "$auth" 2>/dev/null || true
  done
  modprobe usbhid 2>/dev/null || true
  modprobe usb_storage 2>/dev/null || true
  modprobe uas 2>/dev/null || true
  udevadm settle 2>/dev/null || true
  sleep 1
}

mount_usb() {
  authorize_usb_for_offline_media
  mkdir -p "$USB_MNT"
  if findmnt "$USB_MNT" >/dev/null 2>&1; then
    log "USB already mounted at $USB_MNT"
    return 0
  fi
  if [[ -x /usr/local/sbin/mount-offline-usb.sh ]]; then
    if /usr/local/sbin/mount-offline-usb.sh "$LABEL" "$USB_MNT"; then
      return 0
    fi
  fi
  # Also try helper still on media (running from USB before sbin install)
  local self_dir
  self_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [[ -x "$self_dir/mount-offline-usb.sh" ]]; then
    if bash "$self_dir/mount-offline-usb.sh" "$LABEL" "$USB_MNT"; then
      return 0
    fi
  fi
  local dev i
  for i in 1 2 3 4 5 6 8 10; do
    dev="$(blkid -L "$LABEL" 2>/dev/null || true)"
    [[ -n "$dev" ]] && break
    if [[ -n "${USB_UUID:-}" ]]; then
      dev="$(blkid -U "$USB_UUID" 2>/dev/null || true)"
      [[ -n "$dev" ]] && break
    fi
    sleep 1
    authorize_usb_for_offline_media
  done
  if [[ -z "${dev:-}" ]]; then
    echo "ERROR: No filesystem with LABEL=$LABEL found." >&2
    blkid || true
    lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL,PARTLABEL,UUID || true
    exit 1
  fi
  mount -o ro "$dev" "$USB_MNT"
  log "Mounted $dev -> $USB_MNT (ro)"
}

local_mirror_ok() {
  [[ -d "$LOCAL_REPO_ROOT/BaseOS/repodata" || -d "$LOCAL_REPO_ROOT/BaseOS/Packages" ]] && \
  [[ -d "$LOCAL_REPO_ROOT/AppStream/repodata" || -d "$LOCAL_REPO_ROOT/AppStream/Packages" ]]
}

write_repo_file() {
  local base="$1" out="$2" prefix="$3"
  local epel_en=0
  if [[ -d "$base/EPEL/repodata" || -d "$base/EPEL/Packages" ]]; then
    epel_en=1
  fi
  cat > "$out" <<EOF
# Generated by copy-offline-mirror-from-usb.sh on $(date -Is)
[${prefix}-baseos]
name=Offline BaseOS (${base})
baseurl=file://${base}/BaseOS
enabled=1
gpgcheck=0
module_hotfixes=1
[${prefix}-appstream]
name=Offline AppStream (${base})
baseurl=file://${base}/AppStream
enabled=1
gpgcheck=0
module_hotfixes=1
[${prefix}-crb]
name=Offline CodeReady Builder (${base})
baseurl=file://${base}/CodeReadyBuilder
enabled=$( [[ -d "$base/CodeReadyBuilder" ]] && echo 1 || echo 0 )
gpgcheck=0
module_hotfixes=1
[${prefix}-epel]
name=Offline EPEL 8 (${base})
baseurl=file://${base}/EPEL
enabled=${epel_en}
gpgcheck=0
EOF
}

disable_cdn_repos() {
  mkdir -p /etc/yum.repos.d/backup-original
  if command -v subscription-manager >/dev/null 2>&1; then
    subscription-manager repos --disable='*' 2>/dev/null || true
  fi
  local f
  for f in /etc/yum.repos.d/*.repo; do
    [[ -e "$f" ]] || continue
    case "$f" in
      *offline-local.repo|*offline-usb.repo) continue ;;
      *)
        if [[ ! -f "${f}.disabled-by-airgap" ]]; then
          cp -a "$f" /etc/yum.repos.d/backup-original/ 2>/dev/null || true
          mv "$f" "${f}.disabled-by-airgap" 2>/dev/null || true
        fi
        ;;
    esac
  done
}

install_helpers_from() {
  local src="$1"
  if [[ -x "$src/scripts/install-airgap-helpers.sh" ]]; then
    bash "$src/scripts/install-airgap-helpers.sh" "$src" || true
  elif [[ -x /usr/local/sbin/install-airgap-helpers.sh ]]; then
    /usr/local/sbin/install-airgap-helpers.sh "$src" || true
  else
    mkdir -p /usr/local/sbin /usr/local/share/airgap/docs /root/airgap-docs
    local s
    for s in authorize-offline-usb.sh mount-offline-usb.sh enable-offline-repos.sh \
             offline-repo-status.sh configure-grub-timeout.sh \
             copy-offline-mirror-from-usb.sh install-from-local-mirror.sh \
             update-target-repo-from-usb.sh install-airgap-helpers.sh; do
      [[ -f "$src/scripts/$s" ]] && cp -a "$src/scripts/$s" /usr/local/sbin/ && chmod 755 "/usr/local/sbin/$s"
    done
    [[ -d "$src/docs" ]] && cp -a "$src/docs"/. /usr/local/share/airgap/docs/ && cp -a "$src/docs"/. /root/airgap-docs/
    [[ -f "$src/docs/ROOT-HOME-README.md" ]] && cp -a "$src/docs/ROOT-HOME-README.md" /root/README.md
  fi
}

echo
echo "############################################################"
echo "# Step 1/2: copy offline mirror USB → local disk            #"
echo "############################################################"

log "Mounting offline USB (LABEL=$LABEL)"
mount_usb

if [[ ! -d "$USB_MNT/BaseOS" || ! -d "$USB_MNT/AppStream" ]]; then
  echo "ERROR: $USB_MNT does not look like the offline media (need BaseOS/ and AppStream/)." >&2
  ls -la "$USB_MNT" || true
  exit 1
fi

log "Installing air-gap helpers and docs from USB (early)"
install_helpers_from "$USB_MNT"

log "Configuring temporary USB-based dnf repos (bootstrap rsync if needed)"
write_repo_file "$USB_MNT" "$REPO_FILE_USB" "offline-usb"
disable_cdn_repos
write_repo_file "$USB_MNT" "$REPO_FILE_USB" "offline-usb"
dnf clean all >/dev/null 2>&1 || true

if ! command -v rsync >/dev/null 2>&1; then
  log "Installing rsync from USB media (bootstrap)"
  dnf -y --disablerepo='*' --enablerepo='offline-usb-*' install rsync
fi

log "Copying offline repo mirror USB -> local disk (${LOCAL_REPO_ROOT})"
echo "    This can take a while (~30GB+)."
mkdir -p "$LOCAL_REPO_ROOT"

if [[ "$SKIP_REPO_COPY" == "1" ]] && local_mirror_ok; then
  log "SKIP_REPO_COPY=1 and local mirror looks present — not re-copying"
else
  rsync -aH --info=progress2 \
    --exclude='lost+found' \
    "$USB_MNT"/ "$LOCAL_REPO_ROOT"/
fi

if ! local_mirror_ok; then
  echo "ERROR: local mirror incomplete after copy: $LOCAL_REPO_ROOT" >&2
  ls -la "$LOCAL_REPO_ROOT" || true
  exit 1
fi

log "Local mirror size:"
du -sh "$LOCAL_REPO_ROOT" "$LOCAL_REPO_ROOT"/* 2>/dev/null | head -20

log "Re-installing helpers/docs from local mirror (so step 2 does not need USB)"
install_helpers_from "$LOCAL_REPO_ROOT"

log "Configuring permanent dnf sources -> file://${LOCAL_REPO_ROOT}/..."
rm -f "$REPO_FILE_USB"
export LOCAL_REPO_ROOT
if [[ -x /usr/local/sbin/enable-offline-repos.sh ]]; then
  /usr/local/sbin/enable-offline-repos.sh
else
  write_repo_file "$LOCAL_REPO_ROOT" "$REPO_FILE_LOCAL" "offline-local"
  disable_cdn_repos
  write_repo_file "$LOCAL_REPO_ROOT" "$REPO_FILE_LOCAL" "offline-local"
fi
dnf clean all >/dev/null 2>&1 || true

if grep -q "file://${USB_MNT}" /etc/yum.repos.d/*.repo 2>/dev/null; then
  echo "ERROR: A yum repo still points at USB mount $USB_MNT" >&2
  grep -n "file://${USB_MNT}" /etc/yum.repos.d/*.repo || true
  exit 1
fi
if ! grep -q "file://${LOCAL_REPO_ROOT}/BaseOS" "$REPO_FILE_LOCAL" 2>/dev/null; then
  # enable-offline-repos may have written it; re-check
  if [[ ! -f "$REPO_FILE_LOCAL" ]] || ! grep -q "file://${LOCAL_REPO_ROOT}/BaseOS" "$REPO_FILE_LOCAL" 2>/dev/null; then
    write_repo_file "$LOCAL_REPO_ROOT" "$REPO_FILE_LOCAL" "offline-local"
  fi
fi

sync

echo
echo "############################################################"
echo "# Step 1 complete — STOP HERE                                #"
echo "############################################################"
echo
echo "  Local mirror:  $LOCAL_REPO_ROOT"
echo "  dnf repos:     $REPO_FILE_LOCAL"
echo "  Helpers:       /usr/local/sbin/  (install-from-local-mirror.sh is local now)"
echo
echo "  Next (manual):"
echo "    1) sudo umount $USB_MNT"
echo "    2) Unplug the USB stick"
echo "    3) sudo install-from-local-mirror.sh"
echo "       (or: sudo /usr/local/sbin/install-from-local-mirror.sh)"
echo "       (or: sudo bash $LOCAL_REPO_ROOT/scripts/install-from-local-mirror.sh)"
echo
echo "  Do NOT leave this script running — package install is a separate script"
echo "  so it is not interrupted when the USB is removed."
echo
