#!/usr/bin/env bash
# Point dnf at air-gap package sources. Prefers local disk mirror; falls back to USB.
#
#   sudo enable-offline-repos.sh
#   LOCAL_REPO_ROOT=/data/offline-repos sudo enable-offline-repos.sh
#
# Env:
#   LOCAL_REPO_ROOT  default /var/lib/offline-repos
#   USB_REPO_LABEL   default RHEL8OFFLINE
#   USB_MNT          default /mnt/rhel8offline
set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root" >&2
  exit 1
fi

LOCAL="${LOCAL_REPO_ROOT:-/var/lib/offline-repos}"
USB_MNT="${USB_MNT:-/mnt/rhel8offline}"
LABEL="${USB_REPO_LABEL:-RHEL8OFFLINE}"
REPO_LOCAL=/etc/yum.repos.d/offline-local.repo
REPO_USB=/etc/yum.repos.d/offline-usb.repo

if [[ -d "$LOCAL/BaseOS" ]]; then
  BASE="$LOCAL"
  OUT="$REPO_LOCAL"
  PREFIX=offline-local
  rm -f "$REPO_USB"
else
  if [[ -x /usr/local/sbin/mount-offline-usb.sh ]]; then
    /usr/local/sbin/mount-offline-usb.sh "$LABEL" "$USB_MNT" || true
  elif [[ -x /usr/local/sbin/authorize-offline-usb.sh ]]; then
    /usr/local/sbin/authorize-offline-usb.sh >/dev/null 2>&1 || true
    mkdir -p "$USB_MNT"
    if ! findmnt "$USB_MNT" >/dev/null 2>&1; then
      DEV="$(blkid -L "$LABEL" 2>/dev/null || true)"
      [[ -n "$DEV" ]] && mount -o ro "$DEV" "$USB_MNT" || true
    fi
  fi
  BASE="$USB_MNT"
  OUT="$REPO_USB"
  PREFIX=offline-usb
fi

if [[ ! -d "$BASE/BaseOS" && ! -d "$BASE/AppStream" ]]; then
  echo "ERROR: no offline mirror at $LOCAL or $USB_MNT" >&2
  exit 1
fi

EPEL_EN=0
CRB_EN=0
[[ -d "$BASE/EPEL/repodata" || -d "$BASE/EPEL/Packages" ]] && EPEL_EN=1
[[ -d "$BASE/CodeReadyBuilder" ]] && CRB_EN=1

cat > "$OUT" <<EOF
# Generated by enable-offline-repos.sh on $(date -Is)
# Source root: $BASE

[${PREFIX}-baseos]
name=Offline BaseOS
baseurl=file://${BASE}/BaseOS
enabled=1
gpgcheck=0
module_hotfixes=1

[${PREFIX}-appstream]
name=Offline AppStream
baseurl=file://${BASE}/AppStream
enabled=1
gpgcheck=0
module_hotfixes=1

[${PREFIX}-crb]
name=Offline CRB
baseurl=file://${BASE}/CodeReadyBuilder
enabled=${CRB_EN}
gpgcheck=0
module_hotfixes=1

[${PREFIX}-epel]
name=Offline EPEL
baseurl=file://${BASE}/EPEL
enabled=${EPEL_EN}
gpgcheck=0
EOF

# Quiet RHSM / CDN noise on air-gap systems
if command -v subscription-manager >/dev/null 2>&1; then
  subscription-manager repos --disable='*' >/dev/null 2>&1 || true
fi
if [[ -f /etc/dnf/plugins/subscription-manager.conf ]]; then
  sed -i 's/^enabled\s*=\s*1/enabled=0/' /etc/dnf/plugins/subscription-manager.conf 2>/dev/null || true
fi

mkdir -p /etc/yum.repos.d/backup-original
for f in /etc/yum.repos.d/*.repo; do
  [[ -e "$f" ]] || continue
  case "$f" in
    *offline-local.repo|*offline-usb.repo) ;;
    *)
      if [[ ! -f "${f}.disabled-by-airgap" ]]; then
        cp -a "$f" /etc/yum.repos.d/backup-original/ 2>/dev/null || true
        mv "$f" "${f}.disabled-by-airgap" 2>/dev/null || true
      fi
      ;;
  esac
done

# If we wrote offline-local but it got disabled earlier, restore
if [[ -f "${OUT}.disabled-by-airgap" && ! -f "$OUT" ]]; then
  mv "${OUT}.disabled-by-airgap" "$OUT"
fi

dnf clean all >/dev/null 2>&1 || true
echo "Offline repos enabled from: $BASE"
echo "(Unregistered system warnings from subscription-manager are expected offline.)"
echo "Example:  dnf install <pkg>   |   dnf upgrade"
