#!/usr/bin/env bash
# Run on the installed RHEL system with the offline USB inserted (first time).
#
# 1) Mounts USB (LABEL=RHEL8OFFLINE)
# 2) Copies the full repo mirror (+ wheels/docs) to LOCAL disk
# 3) Configures permanent dnf/yum .repo files to use the local copy
# 4) Installs packages / wheels from local disk (USB no longer required after this)
#
# Env overrides:
#   USB_REPO_LABEL   default RHEL8OFFLINE
#   USB_MNT          default /mnt/rhel8offline
#   LOCAL_REPO_ROOT  default /var/lib/offline-repos
#   SKIP_REPO_COPY=1 skip copy if local mirror already present and complete
set -euo pipefail

LABEL="${USB_REPO_LABEL:-RHEL8OFFLINE}"
USB_MNT="${USB_MNT:-${MNT:-/mnt/rhel8offline}}"
LOCAL_REPO_ROOT="${LOCAL_REPO_ROOT:-/var/lib/offline-repos}"
REPO_FILE_LOCAL="/etc/yum.repos.d/offline-local.repo"
REPO_FILE_USB="/etc/yum.repos.d/offline-usb.repo"
SKIP_REPO_COPY="${SKIP_REPO_COPY:-0}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root" >&2
  exit 1
fi

log() { echo "==> $*"; }

mount_usb() {
  mkdir -p "$USB_MNT"
  if findmnt "$USB_MNT" >/dev/null 2>&1; then
    log "USB already mounted at $USB_MNT"
    return 0
  fi
  local dev
  dev="$(blkid -L "$LABEL" 2>/dev/null || true)"
  if [[ -z "$dev" ]]; then
    echo "ERROR: No filesystem with LABEL=$LABEL found. Insert the installer USB." >&2
    blkid || true
    exit 1
  fi
  mount -o ro "$dev" "$USB_MNT"
  log "Mounted $dev -> $USB_MNT (ro)"
}

local_mirror_ok() {
  [[ -d "$LOCAL_REPO_ROOT/BaseOS/repodata" || -d "$LOCAL_REPO_ROOT/BaseOS/Packages" ]] && \
  [[ -d "$LOCAL_REPO_ROOT/AppStream/repodata" || -d "$LOCAL_REPO_ROOT/AppStream/Packages" ]]
}

write_repo_file() {
  # $1 = base path for file:// URLs  $2 = output repo file  $3 = name prefix
  local base="$1" out="$2" prefix="$3"
  local epel_en=0
  if [[ -d "$base/EPEL/repodata" || -d "$base/EPEL/Packages" ]]; then
    epel_en=1
  fi
  cat > "$out" <<EOF
# Generated by post-install-extra.sh on $(date -Is)
# Package sources for air-gapped use (no internet / no subscription CDN required)

[${prefix}-baseos]
name=Offline BaseOS (${base})
baseurl=file://${base}/BaseOS
enabled=1
gpgcheck=0
module_hotfixes=1

[${prefix}-appstream]
name=Offline AppStream (${base})
baseurl=file://${base}/AppStream
enabled=1
gpgcheck=0
module_hotfixes=1

[${prefix}-crb]
name=Offline CodeReady Builder (${base})
baseurl=file://${base}/CodeReadyBuilder
enabled=$( [[ -d "$base/CodeReadyBuilder" ]] && echo 1 || echo 0 )
gpgcheck=0
module_hotfixes=1

[${prefix}-epel]
name=Offline EPEL 8 (${base})
baseurl=file://${base}/EPEL
enabled=${epel_en}
gpgcheck=0
EOF
}

disable_cdn_repos() {
  mkdir -p /etc/yum.repos.d/backup-original
  # Disable RHSM / CDN content so dnf does not try the network
  if command -v subscription-manager >/dev/null 2>&1; then
    subscription-manager repos --disable='*' 2>/dev/null || true
  fi
  local f
  for f in /etc/yum.repos.d/*.repo; do
    [[ -e "$f" ]] || continue
    case "$f" in
      *offline-local.repo|*offline-usb.repo) continue ;;
      *)
        if [[ ! -f "${f}.disabled-by-airgap" ]]; then
          cp -a "$f" /etc/yum.repos.d/backup-original/ 2>/dev/null || true
          mv "$f" "${f}.disabled-by-airgap" 2>/dev/null || true
        fi
        ;;
    esac
  done
}

install_local_helpers() {
  cat > /usr/local/sbin/enable-offline-repos.sh <<EOS
#!/bin/bash
# Enable permanent local-disk offline dnf repos (USB not required).
set -euo pipefail
LOCAL_REPO_ROOT="${LOCAL_REPO_ROOT}"
REPO_FILE="${REPO_FILE_LOCAL}"
if [[ ! -d "\$LOCAL_REPO_ROOT/BaseOS" ]]; then
  echo "Local offline mirror missing at \$LOCAL_REPO_ROOT" >&2
  exit 1
fi
EPEL_EN=0
CRB_EN=0
[[ -d "\$LOCAL_REPO_ROOT/EPEL/repodata" || -d "\$LOCAL_REPO_ROOT/EPEL/Packages" ]] && EPEL_EN=1
[[ -d "\$LOCAL_REPO_ROOT/CodeReadyBuilder" ]] && CRB_EN=1
cat > "\$REPO_FILE" <<EOF
# Permanent air-gap package sources (local disk)
# Root: \$LOCAL_REPO_ROOT
[offline-local-baseos]
name=Offline BaseOS (local disk)
baseurl=file://\$LOCAL_REPO_ROOT/BaseOS
enabled=1
gpgcheck=0
module_hotfixes=1

[offline-local-appstream]
name=Offline AppStream (local disk)
baseurl=file://\$LOCAL_REPO_ROOT/AppStream
enabled=1
gpgcheck=0
module_hotfixes=1

[offline-local-crb]
name=Offline CodeReady Builder (local disk)
baseurl=file://\$LOCAL_REPO_ROOT/CodeReadyBuilder
enabled=\$CRB_EN
gpgcheck=0
module_hotfixes=1

[offline-local-epel]
name=Offline EPEL 8 (local disk)
baseurl=file://\$LOCAL_REPO_ROOT/EPEL
enabled=\$EPEL_EN
gpgcheck=0
EOF
if command -v subscription-manager >/dev/null 2>&1; then
  subscription-manager repos --disable='*' 2>/dev/null || true
fi
for f in /etc/yum.repos.d/*.repo; do
  [[ -e "\$f" ]] || continue
  case "\$f" in
    *offline-local.repo) ;;
    *)
      [[ -f "\${f}.disabled-by-airgap" ]] || mv "\$f" "\${f}.disabled-by-airgap" 2>/dev/null || true
      ;;
  esac
done
# If our file was renamed by the loop, restore it
if [[ -f "\${REPO_FILE}.disabled-by-airgap" && ! -f "\$REPO_FILE" ]]; then
  mv "\${REPO_FILE}.disabled-by-airgap" "\$REPO_FILE"
fi
dnf clean all >/dev/null 2>&1 || true
echo "Offline LOCAL repos enabled:"
echo "  file://\$LOCAL_REPO_ROOT/{BaseOS,AppStream,CodeReadyBuilder,EPEL}"
echo "Example:  dnf install <pkg>   |   dnf upgrade"
EOS
  chmod 755 /usr/local/sbin/enable-offline-repos.sh

  cat > /usr/local/sbin/offline-repo-status.sh <<EOS
#!/bin/bash
LOCAL="${LOCAL_REPO_ROOT}"
echo "Local offline mirror: \$LOCAL"
du -sh "\$LOCAL" 2>/dev/null || echo "(missing)"
for d in BaseOS AppStream CodeReadyBuilder EPEL python-wheels; do
  if [[ -e "\$LOCAL/\$d" ]]; then
    printf '  %-18s %s\n' "\$d" "\$(du -sh "\$LOCAL/\$d" 2>/dev/null | awk '{print \$1}')"
  else
    printf '  %-18s MISSING\n' "\$d"
  fi
done
echo "Repo file: ${REPO_FILE_LOCAL}"
grep -E '^\\[|^baseurl=|^enabled=' "${REPO_FILE_LOCAL}" 2>/dev/null || echo "(not configured)"
EOS
  chmod 755 /usr/local/sbin/offline-repo-status.sh

  mkdir -p /etc/motd.d
  cat > /etc/motd.d/99-offline-repos <<EOF
Air-gapped package cache: ${LOCAL_REPO_ROOT}
  sudo offline-repo-status.sh
  sudo enable-offline-repos.sh
  sudo dnf install <package>
EOF
}

# ---------- main ----------
log "Mounting offline USB (LABEL=$LABEL)"
mount_usb

if [[ ! -d "$USB_MNT/BaseOS" || ! -d "$USB_MNT/AppStream" ]]; then
  echo "ERROR: $USB_MNT does not look like the offline media (need BaseOS/ and AppStream/)." >&2
  ls -la "$USB_MNT" || true
  exit 1
fi

# Temporarily use USB for dnf so we can install rsync if missing before copy
log "Configuring temporary USB-based dnf repos for bootstrap"
write_repo_file "$USB_MNT" "$REPO_FILE_USB" "offline-usb"
disable_cdn_repos
# re-enable our usb repo if disable_cdn moved it
write_repo_file "$USB_MNT" "$REPO_FILE_USB" "offline-usb"
dnf clean all >/dev/null 2>&1 || true

# Ensure rsync exists for efficient copy (pull from USB BaseOS if needed)
if ! command -v rsync >/dev/null 2>&1; then
  log "Installing rsync from USB media"
  dnf -y --disablerepo='*' --enablerepo='offline-usb-*' install rsync
fi

log "Copying offline repo mirror USB -> local disk (${LOCAL_REPO_ROOT})"
echo "    This can take a while (~30GB+)."
mkdir -p "$LOCAL_REPO_ROOT"

if [[ "$SKIP_REPO_COPY" == "1" ]] && local_mirror_ok; then
  log "SKIP_REPO_COPY=1 and local mirror looks present — not re-copying"
else
  # Full tree copy: RPM repos, EPEL, wheels, docs, package lists, scripts
  rsync -aH --info=progress2 \
    --exclude='lost+found' \
    "$USB_MNT"/ "$LOCAL_REPO_ROOT"/
fi

if ! local_mirror_ok; then
  echo "ERROR: local mirror incomplete after copy: $LOCAL_REPO_ROOT" >&2
  ls -la "$LOCAL_REPO_ROOT" || true
  exit 1
fi

log "Local mirror size:"
du -sh "$LOCAL_REPO_ROOT" "$LOCAL_REPO_ROOT"/* 2>/dev/null | head -20

log "Configuring permanent dnf sources -> file://${LOCAL_REPO_ROOT}/..."
# Remove USB-only repo file; use local only
rm -f "$REPO_FILE_USB"
write_repo_file "$LOCAL_REPO_ROOT" "$REPO_FILE_LOCAL" "offline-local"
disable_cdn_repos
# ensure local repo file still present after disable pass
write_repo_file "$LOCAL_REPO_ROOT" "$REPO_FILE_LOCAL" "offline-local"
install_local_helpers
/usr/local/sbin/enable-offline-repos.sh
dnf clean all >/dev/null 2>&1 || true

log "Applying upgrades from LOCAL offline mirror"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' upgrade || true

log "Installing core required packages (from local mirror)"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' install \
  chrony nano bc socat jq python3 python3-pip python3-setuptools \
  python3.11 python3.11-pip python3.11-setuptools \
  tcpdump wireshark wireshark-cli freerdp \
  java-1.8.0-openjdk java-1.8.0-openjdk-devel \
  java-11-openjdk java-11-openjdk-devel \
  java-17-openjdk java-17-openjdk-devel java-17-openjdk-headless \
  vim-enhanced tmux net-tools gedit tree util-linux util-linux-user \
  rsync openssh openssh-server openssh-clients \
  git gitk git-lfs \
  curl wget tar unzip zip bind-utils nmap-ncat

systemctl enable --now sshd 2>/dev/null || systemctl enable sshd 2>/dev/null || true

log "Installing selected extras"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' install \
  iotop sysstat lsof strace bash-completion man-pages man-db \
  firefox evince gnome-terminal gnome-system-monitor \
  psmisc procps-ng which file less diffutils

log "Installing EPEL extras (htop, nload, pv, keepassxc, rdesktop)"
if [[ -d "$LOCAL_REPO_ROOT/EPEL/repodata" || -d "$LOCAL_REPO_ROOT/EPEL/Packages" ]]; then
  dnf -y --disablerepo='*' --enablerepo='offline-local-*' install htop nload pv keepassxc rdesktop
else
  echo "ERROR: EPEL tree missing under $LOCAL_REPO_ROOT/EPEL" >&2
  exit 1
fi

WHEEL_DIR="${LOCAL_REPO_ROOT}/python-wheels"
log "Installing Python wheels offline (pipx) from $WHEEL_DIR"
if [[ -d "$WHEEL_DIR" ]] && compgen -G "$WHEEL_DIR/*.whl" >/dev/null; then
  REQ="$WHEEL_DIR/requirements.txt"
  if [[ -f "$REQ" ]]; then
    python3.11 -m pip install --no-index --find-links="$WHEEL_DIR" -r "$REQ"
  else
    python3.11 -m pip install --no-index --find-links="$WHEEL_DIR" "$WHEEL_DIR"/*.whl
  fi
  python3.11 -m pipx ensurepath 2>/dev/null || true
else
  echo "ERROR: Python wheels not found at $WHEEL_DIR" >&2
  exit 1
fi

log "Installing Server with GUI (if needed)"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' groupinstall "Server with GUI" || \
  dnf -y --disablerepo='*' --enablerepo='offline-local-*' install @graphical-server-environment
systemctl set-default graphical.target || true

# Document location for operators
cat > /root/README-OFFLINE-REPOS.txt <<EOF
Air-gapped package mirror (local disk)
======================================
Location:  ${LOCAL_REPO_ROOT}
Repos file: ${REPO_FILE_LOCAL}

After this post-install, the USB is NOT required for dnf install/upgrade.

Commands:
  sudo offline-repo-status.sh
  sudo enable-offline-repos.sh
  sudo dnf install <package>
  sudo dnf upgrade

Python wheels:
  ${LOCAL_REPO_ROOT}/python-wheels
  python3.11 -m pip install --no-index --find-links=${LOCAL_REPO_ROOT}/python-wheels -r ${LOCAL_REPO_ROOT}/python-wheels/requirements.txt

Docs (if copied):
  ${LOCAL_REPO_ROOT}/docs/OFFLINE-INSTALL.md
  ${LOCAL_REPO_ROOT}/OFFLINE-INSTALL.md
EOF

log "Post-install complete."
echo "  Local mirror:  $LOCAL_REPO_ROOT  ($(du -sh "$LOCAL_REPO_ROOT" | awk '{print $1}'))"
echo "  dnf repos:     $REPO_FILE_LOCAL  (file:// local disk)"
echo "  Status:        sudo offline-repo-status.sh"
echo "  Re-enable:     sudo enable-offline-repos.sh"
echo "  USB may now be removed."
rpm -qa | wc -l | xargs -I{} echo "  Installed RPMs: {}"
systemctl is-active sshd 2>/dev/null | xargs -I{} echo "  sshd: {}" || true
python3.11 -m pip show pipx 2>/dev/null | head -2 || true
