#!/usr/bin/env bash
# Run on the installed RHEL system with the offline USB inserted (first time).
#
# Phase A (USB required):
#   1) Mount USB (LABEL=RHEL8OFFLINE)
#   2) Copy full repo mirror (+ wheels/docs) to LOCAL disk
#   3) Configure permanent dnf .repo files -> local disk
#   4) Unmount USB  << you may remove the stick here
#
# Phase B (USB not required — long running):
#   5) dnf upgrade + package installs + wheels + GUI from local disk
#
# Env overrides:
#   USB_REPO_LABEL   default RHEL8OFFLINE
#   USB_MNT          default /mnt/rhel8offline
#   LOCAL_REPO_ROOT  default /var/lib/offline-repos
#   SKIP_REPO_COPY=1 skip copy if local mirror already present and complete
#   SKIP_USB_UNMOUNT=1  leave USB mounted after copy (default: unmount)
set -euo pipefail

LABEL="${USB_REPO_LABEL:-RHEL8OFFLINE}"
USB_MNT="${USB_MNT:-${MNT:-/mnt/rhel8offline}}"
LOCAL_REPO_ROOT="${LOCAL_REPO_ROOT:-/var/lib/offline-repos}"
REPO_FILE_LOCAL="/etc/yum.repos.d/offline-local.repo"
REPO_FILE_USB="/etc/yum.repos.d/offline-usb.repo"
SKIP_REPO_COPY="${SKIP_REPO_COPY:-0}"
SKIP_USB_UNMOUNT="${SKIP_USB_UNMOUNT:-0}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root" >&2
  exit 1
fi

log() { echo "==> $*"; }

authorize_usb_for_offline_media() {
  # Confirmed on target STIG image: stop usbguard + authorized_default=1 + modprobe usbhid uas
  if [[ -x /usr/local/sbin/authorize-offline-usb.sh ]]; then
    log "Running authorize-offline-usb.sh"
    /usr/local/sbin/authorize-offline-usb.sh || true
    return 0
  fi
  # Inline fallback (same policy)
  log "USB authorize (inline): stop USBGuard, authorize devices, load hid/storage"
  systemctl stop usbguard.service usbguard-dbus.service 2>/dev/null || true
  systemctl disable usbguard.service usbguard-dbus.service 2>/dev/null || true
  if [[ -f /sys/module/usbcore/parameters/authorized_default ]]; then
    echo 1 > /sys/module/usbcore/parameters/authorized_default 2>/dev/null || true
  fi
  for auth in /sys/bus/usb/devices/*/authorized; do
    [[ -f "$auth" ]] && echo 1 > "$auth" 2>/dev/null || true
  done
  modprobe usbhid 2>/dev/null || true
  modprobe usb_storage 2>/dev/null || true
  modprobe uas 2>/dev/null || true
  udevadm settle 2>/dev/null || true
  sleep 1
}

mount_usb() {
  authorize_usb_for_offline_media
  mkdir -p "$USB_MNT"
  if findmnt "$USB_MNT" >/dev/null 2>&1; then
    log "USB already mounted at $USB_MNT"
    return 0
  fi
  local dev
  # Retry a few times after authorization (udev/block layer needs a moment)
  local i
  for i in 1 2 3 4 5 6 8 10; do
    dev="$(blkid -L "$LABEL" 2>/dev/null || true)"
    [[ -n "$dev" ]] && break
    sleep 1
    authorize_usb_for_offline_media
  done
  if [[ -z "$dev" ]]; then
    echo "ERROR: No filesystem with LABEL=$LABEL found after USB authorize." >&2
    echo "dmesg (usb/authoriz):" >&2
    dmesg 2>/dev/null | tail -n 30 | grep -iE 'usb|authoriz|storage' || dmesg | tail -n 20 || true
    echo "Try: sudo /usr/local/sbin/authorize-offline-usb.sh" >&2
    echo "     (copy that script from the build host if not installed yet)" >&2
    blkid || true
    lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL || true
    exit 1
  fi
  mount -o ro "$dev" "$USB_MNT"
  log "Mounted $dev -> $USB_MNT (ro)"
}

local_mirror_ok() {
  [[ -d "$LOCAL_REPO_ROOT/BaseOS/repodata" || -d "$LOCAL_REPO_ROOT/BaseOS/Packages" ]] && \
  [[ -d "$LOCAL_REPO_ROOT/AppStream/repodata" || -d "$LOCAL_REPO_ROOT/AppStream/Packages" ]]
}

write_repo_file() {
  # $1 = base path for file:// URLs  $2 = output repo file  $3 = name prefix
  local base="$1" out="$2" prefix="$3"
  local epel_en=0
  if [[ -d "$base/EPEL/repodata" || -d "$base/EPEL/Packages" ]]; then
    epel_en=1
  fi
  cat > "$out" <<EOF
# Generated by post-install-extra.sh on $(date -Is)
# Package sources for air-gapped use (no internet / no subscription CDN required)

[${prefix}-baseos]
name=Offline BaseOS (${base})
baseurl=file://${base}/BaseOS
enabled=1
gpgcheck=0
module_hotfixes=1

[${prefix}-appstream]
name=Offline AppStream (${base})
baseurl=file://${base}/AppStream
enabled=1
gpgcheck=0
module_hotfixes=1

[${prefix}-crb]
name=Offline CodeReady Builder (${base})
baseurl=file://${base}/CodeReadyBuilder
enabled=$( [[ -d "$base/CodeReadyBuilder" ]] && echo 1 || echo 0 )
gpgcheck=0
module_hotfixes=1

[${prefix}-epel]
name=Offline EPEL 8 (${base})
baseurl=file://${base}/EPEL
enabled=${epel_en}
gpgcheck=0
EOF
}

disable_cdn_repos() {
  mkdir -p /etc/yum.repos.d/backup-original
  # Disable RHSM / CDN content so dnf does not try the network
  if command -v subscription-manager >/dev/null 2>&1; then
    subscription-manager repos --disable='*' 2>/dev/null || true
  fi
  local f
  for f in /etc/yum.repos.d/*.repo; do
    [[ -e "$f" ]] || continue
    case "$f" in
      *offline-local.repo|*offline-usb.repo) continue ;;
      *)
        if [[ ! -f "${f}.disabled-by-airgap" ]]; then
          cp -a "$f" /etc/yum.repos.d/backup-original/ 2>/dev/null || true
          mv "$f" "${f}.disabled-by-airgap" 2>/dev/null || true
        fi
        ;;
    esac
  done
}

# Install helpers/docs from a media root (single path — no duplicated heredocs)
install_helpers_from() {
  local src="$1"
  if [[ -x "$src/scripts/install-airgap-helpers.sh" ]]; then
    bash "$src/scripts/install-airgap-helpers.sh" "$src" || true
  elif [[ -x /usr/local/sbin/install-airgap-helpers.sh ]]; then
    /usr/local/sbin/install-airgap-helpers.sh "$src" || true
  else
    mkdir -p /usr/local/sbin /usr/local/share/airgap/docs /root/airgap-docs
    local s
    for s in authorize-offline-usb.sh mount-offline-usb.sh enable-offline-repos.sh \
             offline-repo-status.sh post-install-extra.sh update-target-repo-from-usb.sh \
             install-airgap-helpers.sh; do
      [[ -f "$src/scripts/$s" ]] && cp -a "$src/scripts/$s" /usr/local/sbin/ && chmod 755 "/usr/local/sbin/$s"
    done
    [[ -d "$src/docs" ]] && cp -a "$src/docs"/. /usr/local/share/airgap/docs/ && cp -a "$src/docs"/. /root/airgap-docs/
    [[ -f "$src/docs/ROOT-HOME-README.md" ]] && cp -a "$src/docs/ROOT-HOME-README.md" /root/README.md
  fi
}

# ---------- main ----------
echo
echo "############################################################"
echo "# Phase A: copy offline mirror to local disk (USB required) #"
echo "############################################################"

log "Mounting offline USB (LABEL=$LABEL)"
mount_usb

if [[ ! -d "$USB_MNT/BaseOS" || ! -d "$USB_MNT/AppStream" ]]; then
  echo "ERROR: $USB_MNT does not look like the offline media (need BaseOS/ and AppStream/)." >&2
  ls -la "$USB_MNT" || true
  exit 1
fi

# EARLIEST possible: install all target scripts + docs from USB (before long rsync)
log "Installing air-gap helpers and docs from USB (early)"
install_helpers_from "$USB_MNT"

# Temporarily use USB for dnf only if we need rsync for the copy
log "Configuring temporary USB-based dnf repos for bootstrap (rsync only if missing)"
write_repo_file "$USB_MNT" "$REPO_FILE_USB" "offline-usb"
disable_cdn_repos
write_repo_file "$USB_MNT" "$REPO_FILE_USB" "offline-usb"
dnf clean all >/dev/null 2>&1 || true

if ! command -v rsync >/dev/null 2>&1; then
  log "Installing rsync from USB media (bootstrap)"
  dnf -y --disablerepo='*' --enablerepo='offline-usb-*' install rsync
fi

log "Copying offline repo mirror USB -> local disk (${LOCAL_REPO_ROOT})"
echo "    This can take a while (~30GB+). Package installs start AFTER USB is unmounted."
mkdir -p "$LOCAL_REPO_ROOT"

if [[ "$SKIP_REPO_COPY" == "1" ]] && local_mirror_ok; then
  log "SKIP_REPO_COPY=1 and local mirror looks present — not re-copying"
else
  rsync -aH --info=progress2 \
    --exclude='lost+found' \
    "$USB_MNT"/ "$LOCAL_REPO_ROOT"/
fi

if ! local_mirror_ok; then
  echo "ERROR: local mirror incomplete after copy: $LOCAL_REPO_ROOT" >&2
  ls -la "$LOCAL_REPO_ROOT" || true
  exit 1
fi

log "Local mirror size:"
du -sh "$LOCAL_REPO_ROOT" "$LOCAL_REPO_ROOT"/* 2>/dev/null | head -20

# Re-install helpers from local mirror (authoritative post-copy; single installer)
log "Re-installing helpers/docs from local mirror"
install_helpers_from "$LOCAL_REPO_ROOT"

log "Configuring permanent dnf sources -> file://${LOCAL_REPO_ROOT}/..."
rm -f "$REPO_FILE_USB"
export LOCAL_REPO_ROOT
if [[ -x /usr/local/sbin/enable-offline-repos.sh ]]; then
  /usr/local/sbin/enable-offline-repos.sh
else
  write_repo_file "$LOCAL_REPO_ROOT" "$REPO_FILE_LOCAL" "offline-local"
  disable_cdn_repos
  write_repo_file "$LOCAL_REPO_ROOT" "$REPO_FILE_LOCAL" "offline-local"
fi
dnf clean all >/dev/null 2>&1 || true

# Sync and release the USB so it can be unplugged before package install
sync
if [[ "$SKIP_USB_UNMOUNT" != "1" ]]; then
  log "Unmounting USB media at $USB_MNT"
  if findmnt "$USB_MNT" >/dev/null 2>&1; then
    umount "$USB_MNT" 2>/dev/null || umount -l "$USB_MNT" 2>/dev/null || true
  fi
  # Also drop any bind mounts under the same path
  while findmnt "$USB_MNT" >/dev/null 2>&1; do
    umount "$USB_MNT" 2>/dev/null || umount -l "$USB_MNT" 2>/dev/null || break
  done
  echo
  echo "############################################################"
  echo "# USB is unmounted and may be REMOVED now.                 #"
  echo "# Local mirror: ${LOCAL_REPO_ROOT}                         #"
  echo "# dnf repos:    ${REPO_FILE_LOCAL}                         #"
  echo "# Starting package installation from local disk next...    #"
  echo "############################################################"
  echo
  sleep 2
else
  log "SKIP_USB_UNMOUNT=1 — leaving USB mounted at $USB_MNT"
fi

# Verify we are NOT depending on USB paths for dnf
if grep -q "file://${USB_MNT}" /etc/yum.repos.d/*.repo 2>/dev/null; then
  echo "ERROR: A yum repo still points at USB mount $USB_MNT" >&2
  grep -n "file://${USB_MNT}" /etc/yum.repos.d/*.repo || true
  exit 1
fi
if ! grep -q "file://${LOCAL_REPO_ROOT}/BaseOS" "$REPO_FILE_LOCAL" 2>/dev/null; then
  echo "ERROR: offline-local.repo does not point at local BaseOS" >&2
  exit 1
fi

echo
echo "############################################################"
echo "# Phase B: install packages from local disk (USB optional) #"
echo "############################################################"

log "Applying upgrades from LOCAL offline mirror"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' upgrade || true

log "Installing core required packages (from local mirror)"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' install \
  chrony nano bc socat jq python3 python3-pip python3-setuptools \
  python3.11 python3.11-pip python3.11-setuptools \
  tcpdump wireshark wireshark-cli freerdp \
  java-1.8.0-openjdk java-1.8.0-openjdk-devel \
  java-11-openjdk java-11-openjdk-devel \
  java-17-openjdk java-17-openjdk-devel java-17-openjdk-headless \
  vim-enhanced tmux net-tools gedit tree util-linux util-linux-user \
  rsync openssh openssh-server openssh-clients \
  git gitk git-lfs \
  curl wget tar unzip zip bind-utils nmap-ncat

systemctl enable --now sshd 2>/dev/null || systemctl enable sshd 2>/dev/null || true

log "Installing selected extras"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' install \
  iotop sysstat lsof strace bash-completion man-pages man-db \
  firefox evince gnome-terminal gnome-system-monitor \
  psmisc procps-ng which file less diffutils

log "Installing EPEL extras (htop, nload, pv, keepassxc, rdesktop)"
if [[ -d "$LOCAL_REPO_ROOT/EPEL/repodata" || -d "$LOCAL_REPO_ROOT/EPEL/Packages" ]]; then
  dnf -y --disablerepo='*' --enablerepo='offline-local-*' install htop nload pv keepassxc rdesktop
else
  echo "ERROR: EPEL tree missing under $LOCAL_REPO_ROOT/EPEL" >&2
  exit 1
fi

WHEEL_DIR="${LOCAL_REPO_ROOT}/python-wheels"
log "Installing Python wheels offline (pipx) from $WHEEL_DIR"
if [[ -d "$WHEEL_DIR" ]] && compgen -G "$WHEEL_DIR/*.whl" >/dev/null; then
  REQ="$WHEEL_DIR/requirements.txt"
  if [[ -f "$REQ" ]]; then
    python3.11 -m pip install --no-index --find-links="$WHEEL_DIR" -r "$REQ"
  else
    python3.11 -m pip install --no-index --find-links="$WHEEL_DIR" "$WHEEL_DIR"/*.whl
  fi
  python3.11 -m pipx ensurepath 2>/dev/null || true
else
  echo "ERROR: Python wheels not found at $WHEEL_DIR" >&2
  exit 1
fi

log "Installing Server with GUI (if needed)"
dnf -y --disablerepo='*' --enablerepo='offline-local-*' groupinstall "Server with GUI" || \
  dnf -y --disablerepo='*' --enablerepo='offline-local-*' install @graphical-server-environment
systemctl set-default graphical.target || true

# Final helper/doc refresh from local mirror (keeps /root/README.md + sbin in sync)
log "Final helpers/docs refresh from local mirror"
install_helpers_from "$LOCAL_REPO_ROOT"
export LOCAL_REPO_ROOT
[[ -x /usr/local/sbin/enable-offline-repos.sh ]] && /usr/local/sbin/enable-offline-repos.sh || true

log "Post-install complete (packages installed from local disk)."
echo "  Local mirror:  $LOCAL_REPO_ROOT  ($(du -sh "$LOCAL_REPO_ROOT" | awk '{print $1}'))"
echo "  dnf repos:     $REPO_FILE_LOCAL  (file:// local disk)"
echo "  Root guide:    /root/README.md"
echo "  Docs:          /usr/local/share/airgap/docs/  and  /root/airgap-docs/"
echo "  Status:        sudo offline-repo-status.sh"
echo "  USB:           already unmounted (unless SKIP_USB_UNMOUNT=1)"
rpm -qa | wc -l | xargs -I{} echo "  Installed RPMs: {}"
systemctl is-active sshd 2>/dev/null | xargs -I{} echo "  sshd: {}" || true
python3.11 -m pip show pipx 2>/dev/null | head -2 || true